name: mirror

on:
  push:
  
  schedule:
    - cron: '10 * * * *'
    
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: clone/checkout the code
        uses: actions/checkout@v2
      - name: check the current version
        run: |
          current_version=$(curl -sN http://www.live555.com/liveMedia/public/changelog.txt | head -n 1 | tr ":" "\0")
          echo "current_version: $current_version"
          previous_version=$(cat changelog.txt | head -n 1 | tr ":" "\0")
          echo "previous_version: $previous_version"
          ccv=$(echo $current_version | tr "." "\0")
          cpv=$(echo $previous_version | tr "." "\0")
          
          current_version=$(curl -sN http://www.live555.com/liveMedia/public/changelog.txt | head -n 1 | tr ":" "\0")
          echo "current_version: $current_version"
          
          if [ -f changelog.txt ]; then
            echo -e "file found"
            previous_version=$(cat changelog.txt | head -n 1 | tr ":" "\0")
            cpv=$(echo $previous_version | tr "." "\0")
          else
            previous_version=0
            cpv=0
          fi
          
          echo "previous_version: $previous_version"
          ccv=$(echo ${current_version} | tr "." "\0")
          echo "ccv: $ccv"

          if [[ ccv -gt cpv ]]; then
            echo -e "current version is greater"
            wget http://www.live555.com/liveMedia/public/live.${current_version}.tar.gz
            rm -rf * 
            tar -xzf live.${current_version}.tar.gz
            git status
            git add .
            git commit -m "code change"
            git push
          else
            echo -e "current version is same"
          fi
